ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20);
ALTER TABLE users ALTER COLUMN score TYPE DECIMAL(10,2);
ALTER TABLE users ALTER COLUMN score SET DEFAULT 0.0;

ALTER TYPE post_status RENAME VALUE 'POSTED' TO 'JUST_POSTED';
ALTER TYPE post_status RENAME VALUE 'IN_PROGRESS' TO 'FIRST_REACTIONS';
ALTER TYPE post_status RENAME VALUE 'RESOLVED' TO 'EXPIRED';

ALTER TABLE posts ALTER COLUMN status SET DEFAULT 'JUST_POSTED';

UPDATE posts SET image_url = '' WHERE image_url IS NULL;
ALTER TABLE posts ALTER COLUMN image_url SET NOT NULL;