GET http://localhost:8080/users
Authorization: Basic user 700aa233-d8b9-4c74-a3a9-5a4df9c046ec

###

POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Basic user 5a90255a-170f-4e4b-ba92-206ec5d8b15a

{
  "userId": 2,
  "title": "Test",
  "text": "HelloWorld",
  "imageUrl": "https://link-imagine.ro/test.jpg"
}

###

PUT http://localhost:8080/posts/2
Content-Type: application/json
Authorization: Basic user 5a90255a-170f-4e4b-ba92-206ec5d8b15a

{
  "title": "Modified",
  "text": "Update done",
  "imageUrl": "https://link-imagine.ro/noua-poza.jpg"
}

###


DELETE http://localhost:8080/posts/2
Authorization: Basic user 5a90255a-170f-4e4b-ba92-206ec5d8b15a

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic user 5a90255a-170f-4e4b-ba92-206ec5d8b15a

{
  "username": "test",
  "email": "test@cluj.ro",
  "password": "parola123",
  "fullName": "Student Test"
}